services:
  - type: web
    name: bladecraft-fencing-store
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 26
      - key: BASE_URL
        sync: false
      - key: SHOPIFY_STORE_DOMAIN
        sync: false
      - key: SHOPIFY_STOREFRONT_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_API_VERSION
        value: 2026-01
